// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config"
import { defineConfig } from "prisma/config"

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx scripts/seed-system-voices.ts",
  },
  datasource: {
    // Migrations require a direct connection (no pgbouncer).
    // Use DIRECT_URL here; DATABASE_URL (pooler) is used by PrismaClient at runtime.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
})
