/**
 * Reads the local OpenAPI spec and generates TypeScript types.
 *
 * Usage:
 *   npm run sync-api
 */

import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

import openapiTS, { astToString } from "openapi-typescript"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const OPENAPI_PATH = path.resolve(__dirname, "../openapi.json")
const OUTPUT_PATH = path.resolve(__dirname, "../src/types/chatterbox-api.d.ts")

async function main() {
  if (!fs.existsSync(OPENAPI_PATH)) {
    console.error(`Error: OpenAPI file not found at ${OPENAPI_PATH}`)
    process.exit(1)
  }

  console.log(`Reading OpenAPI spec from: ${OPENAPI_PATH}`)
  const openApiSchema = JSON.parse(fs.readFileSync(OPENAPI_PATH, "utf-8"))

  const ast = await openapiTS(openApiSchema)
  const contents = astToString(ast)

  // Ensure output directory exists
  const outputDir = path.dirname(OUTPUT_PATH)
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true })
  }

  // Add header comment
  const header = `/**
* This file is auto-generated by scripts/sync-api.ts
* Do not edit manually. Run \`npm run sync-api\` to regenerate.
*
* Generated from: ${OPENAPI_PATH}
* Generated at: ${new Date().toISOString()}
*/
  `

  fs.writeFileSync(OUTPUT_PATH, header + contents)
  console.log(`Types written to: ${OUTPUT_PATH}`)
}

main().catch((err) => {
  console.error("Failed to sync API types:", err)
  process.exit(1)
})
